# Generated by Django 4.0.8 on 2022-10-05 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='date_retrieved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
