# Generated by Django 4.0.8 on 2022-10-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='num_stars',
            field=models.FloatField(max_length=30),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='num_stars',
            field=models.FloatField(max_length=30),
        ),
    ]
