# Generated by Django 4.0.8 on 2022-10-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='reference_id',
            field=models.CharField(default='default', max_length=500),
            preserve_default=False,
        ),
    ]
