# Generated by Django 4.0.8 on 2022-10-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_pricehistory_date_retrieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='num_stars',
            field=models.FloatField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_date',
            field=models.DateField(blank=True),
        ),
    ]
